#!/bin/sh
# set-ssh-askpass
# This file is part of ssh-askpass-mac

launchctl setenv SSH_ASKPASS /Applications/ssh-askpass.app/Contents/MacOS/ssh-askpass
launchctl setenv SSH_ASKPASS_REQUIRE force
[[ -z "${DISPLAY+set}" ]] && launchctl setenv DISPLAY invalid # required by OpenSSH lower than 8.3
launchctl stop com.openssh.ssh-agent
